travis:
  secure:
    BINSTAR_TOKEN: qDgbqh2MVPnaqLNYo4e9yRsRql94XpqmeWsGqLhsuZc5PLQTpbWNacuDFhzuIIpSH/PVvkJ0868x0kyYve5l63J2E6hZbBB2B7iZEuc+XNdr2Dy54lFBczTkdWDq4fFy0dPM09ULS5kBU54jL5Ui4RMiIJ2750blD4CPhtYXE2PkZfrH4mNuvSmkpieaJOcDq+VBfZ3tEiJ+7XNjLJE8zs/NcnkPbygbUMSC5WABaTNE8kXxGSViiWEJ1STeQ6Mvxe79TjfJfGEVnXF3KmX41/Pa5PqtbjfPw/SAPqVm1FWGjjYlBKVgqpwI0ixq9ZwEWQStbUGgSlA07F1+Rmmxi81G/hU59rtS50Uf3XU3dqiUUq7dadOTUrrw1ePIw7KuLDbJuSTyN/c4IAuOV/5j7IUatMHd14c6OmLebdRU5VfyJQOZBO0FwWsvcCr5h5fPlPGoC2l+xDM6Bk8m369T/t6gS7yGJqhdP+Q2IK2G9odQ8ZBGwT37Taaw1iGUFlBhHDMFDuIBthsd88iFUOCWnXvKKmFpQmCgZfX8wX665wlQrpJKlmEhJpcAEeGTW/tODVHyeauqyh4ZMDdqBX1Rn47baHw58Qb9IYmsMt1pxbhhmPbUMKcoKtNPVuYsapNFjCn5vV4JV36Rr24aAEtRBBZdYgxiZJN+QPJfZZm2MOo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
